name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  updates:
    name: Deploy to GitHub pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Prepare node env
        run : echo 'REACT_APP_BASE_URL=https://sakata1222.github.io/sql-formatter-gui/' >> .env

      - name: Prepare node env for PR
        if: github.event_name == 'pull_request'
        run : echo 'REACT_APP_BASE_URL=https://sakata1222.github.io/sql-formatter-gui/pr' >> .env

      - name: Build
        run : |
          yarn install --production --frozen-lockfile
          yarn build
          pwd
          ls

      - name: Move if PR
        if: github.event_name == 'pull_request'
        run : |
          mkdir build_pr
          mv build/* build_pr/
          mkdir build/pr
          mv build_pr/* build/pr
          find /home/runner/work/sql-formatter-gui/sql-formatter-gui/build/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
