name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  updates:
    name: Deploy to GitHub pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup node
        uses: actions/setup-node@v7
        with:
          cache: 'pnpm'

      - name: Build
        run : |
          pnpm install --frozen-lockfile
          pnpm build --base=/sql-formatter-gui/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
