name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  updates:
    name: Deploy to GitHub pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Build
        run : |
          yarn install --production --frozen-lockfile
          PUBLIC_URL=https://sakata1222.github.io/sql-formatter-gui/ yarn build
